import type { ComponentDependency, ComponentRegistryEntry, ComponentSourceFile } from "./schema.js";

const motionDependencies = [
  { name: "animejs", type: "npm", version: "4.5.0" },
  { name: "easecraft-tokens", type: "workspace", version: "0.0.0" },
  { name: "react", type: "peer", version: ">=18.2.0 <20.0.0" },
  { name: "react-dom", type: "peer", version: ">=18.2.0 <20.0.0" },
] as const satisfies readonly ComponentDependency[];

function withRadixDependency(name: string, version: string): readonly ComponentDependency[] {
  return [{ name, type: "npm", version }, ...motionDependencies];
}

function sourceFiles(name: string, integration = true): readonly ComponentSourceFile[] {
  return [
    { path: `src/${name}.tsx`, role: "implementation" },
    { path: `src/${name}.test.tsx`, role: "unit-test" },
    ...(integration
      ? ([{ path: `src/${name}.integration.test.tsx`, role: "integration-test" }] as const)
      : []),
  ];
}

export const componentEntries = [
  {
    accessibility: {
      announcement: "none",
      focusManagement: false,
      keyboard: [],
      notes: [
        "Preserves readable source text before client enhancement.",
        "Split visual segments do not create repeated screen-reader output.",
      ],
      pattern: "text",
    },
    category: "Text",
    dependencies: motionDependencies,
    description: "Word-level entrance with readable source text.",
    docsPath: "/components/text-reveal",
    exportName: "TextReveal",
    motion: {
      controlled: false,
      enter: true,
      exit: false,
      intrinsicSize: false,
      layout: false,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Text Reveal",
    packageName: "easecraft",
    slug: "text-reveal",
    sourceFiles: sourceFiles("text-reveal"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "configurable",
      focusManagement: false,
      keyboard: [],
      notes: [
        "Keeps the final semantic value separate from transient visual frames.",
        "Live announcements are opt-in and use the final formatted value.",
      ],
      pattern: "status",
    },
    category: "Feedback",
    dependencies: motionDependencies,
    description: "Numeric transitions with stable final output.",
    docsPath: "/components/number-ticker",
    exportName: "NumberTicker",
    motion: {
      controlled: true,
      enter: true,
      exit: false,
      intrinsicSize: false,
      layout: false,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Number Ticker",
    packageName: "easecraft",
    slug: "number-ticker",
    sourceFiles: sourceFiles("number-ticker"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "none",
      focusManagement: true,
      keyboard: [
        {
          behavior: "Native focus order remains stable while keyed items enter, move, or exit.",
          keys: ["Tab", "Shift+Tab"],
        },
      ],
      notes: [
        "Preserves list semantics and keyed DOM identity.",
        "Transfers focus before an exiting item becomes inert.",
      ],
      pattern: "list",
    },
    category: "Layout",
    dependencies: motionDependencies,
    description: "Insertion and removal with bounded stagger.",
    docsPath: "/components/staggered-list",
    exportName: "StaggeredList",
    motion: {
      controlled: true,
      enter: true,
      exit: true,
      intrinsicSize: false,
      layout: true,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Staggered List",
    packageName: "easecraft",
    slug: "staggered-list",
    sourceFiles: sourceFiles("staggered-list"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "none",
      focusManagement: true,
      keyboard: [
        {
          behavior: "Moves focus between enabled tabs according to orientation.",
          keys: ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"],
        },
        { behavior: "Moves focus to the first or last enabled tab.", keys: ["Home", "End"] },
        {
          behavior: "Activates the focused tab when manual activation is enabled.",
          keys: ["Enter", "Space"],
        },
      ],
      notes: [
        "Uses linked tab and tabpanel semantics with roving focus.",
        "Disabled tabs are skipped during keyboard navigation.",
      ],
      pattern: "tabs",
    },
    category: "Layout",
    dependencies: motionDependencies,
    description: "Keyboard-ready panels with a moving indicator.",
    docsPath: "/components/animated-tabs",
    exportName: "AnimatedTabs",
    motion: {
      controlled: true,
      enter: true,
      exit: false,
      intrinsicSize: false,
      layout: true,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Animated Tabs",
    packageName: "easecraft",
    slug: "animated-tabs",
    sourceFiles: sourceFiles("animated-tabs"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "none",
      focusManagement: true,
      keyboard: [
        { behavior: "Cycles focus within the modal content.", keys: ["Tab", "Shift+Tab"] },
        { behavior: "Requests dismissal when the dialog is dismissible.", keys: ["Escape"] },
      ],
      notes: [
        "Uses modal dialog semantics with linked title and description.",
        "Traps focus while open and restores trigger focus after the retained exit.",
      ],
      pattern: "dialog",
    },
    category: "Overlay",
    dependencies: withRadixDependency("@radix-ui/react-dialog", "1.1.23"),
    description: "Focus-safe presence with retained exit content.",
    docsPath: "/components/motion-dialog",
    exportName: "MotionDialog",
    motion: {
      controlled: true,
      enter: true,
      exit: true,
      intrinsicSize: false,
      layout: false,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Motion Dialog",
    packageName: "easecraft",
    slug: "motion-dialog",
    sourceFiles: sourceFiles("motion-dialog"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "configurable",
      focusManagement: true,
      keyboard: [
        { behavior: "Moves focus to the notification viewport.", keys: ["F8"] },
        { behavior: "Dismisses the active notification.", keys: ["Escape"] },
        { behavior: "Moves through actions and close controls.", keys: ["Tab", "Shift+Tab"] },
      ],
      notes: [
        "Supports polite and assertive notification priorities.",
        "Pauses auto-dismiss timers while the viewport is hovered, focused, or the window is blurred.",
      ],
      pattern: "toast",
    },
    category: "Feedback",
    dependencies: withRadixDependency("@radix-ui/react-toast", "1.2.23"),
    description: "Live-region notifications with controlled reflow.",
    docsPath: "/components/toast-stack",
    exportName: "ToastStack",
    motion: {
      controlled: true,
      enter: true,
      exit: true,
      intrinsicSize: false,
      layout: true,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Toast Stack",
    packageName: "easecraft",
    slug: "toast-stack",
    sourceFiles: sourceFiles("toast-stack"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "polite",
      focusManagement: true,
      keyboard: [
        {
          behavior: "Moves through native filter controls and interactive results.",
          keys: ["Tab"],
        },
        { behavior: "Activates the focused native filter button.", keys: ["Enter", "Space"] },
      ],
      notes: [
        "Announces the target result count in one polite live region.",
        "Filtered exits become inert and transfer focus before removal.",
      ],
      pattern: "filter",
    },
    category: "Layout",
    dependencies: motionDependencies,
    description: "Focus-safe filtering with animated grid reflow.",
    docsPath: "/components/filter-grid",
    exportName: "FilterGrid",
    motion: {
      controlled: true,
      enter: true,
      exit: true,
      intrinsicSize: false,
      layout: true,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Filter Grid",
    packageName: "easecraft",
    slug: "filter-grid",
    sourceFiles: sourceFiles("filter-grid"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "none",
      focusManagement: false,
      keyboard: [],
      notes: [
        "Renders visible semantic content before client enhancement.",
        "Skips observation and animation when reduced motion is active or IntersectionObserver is unavailable.",
      ],
      pattern: "content",
    },
    category: "Layout",
    dependencies: motionDependencies,
    description: "Bounded viewport reveals with visible fallback content.",
    docsPath: "/components/scroll-reveal",
    exportName: "ScrollReveal",
    motion: {
      controlled: false,
      enter: true,
      exit: false,
      intrinsicSize: false,
      layout: false,
      reducedMotion: true,
      replay: true,
      viewport: true,
    },
    name: "Scroll Reveal",
    packageName: "easecraft",
    slug: "scroll-reveal",
    sourceFiles: sourceFiles("scroll-reveal"),
    status: "implemented",
  },
  {
    accessibility: {
      announcement: "none",
      focusManagement: true,
      keyboard: [
        {
          behavior: "Moves focus between enabled accordion triggers.",
          keys: ["ArrowUp", "ArrowDown"],
        },
        { behavior: "Moves focus to the first or last enabled trigger.", keys: ["Home", "End"] },
        { behavior: "Toggles the focused accordion panel.", keys: ["Enter", "Space"] },
      ],
      notes: [
        "Maintains stable heading, trigger, and region relationships.",
        "Closing content becomes inert and returns focus to its trigger when necessary.",
      ],
      pattern: "accordion",
    },
    category: "Layout",
    dependencies: withRadixDependency("@radix-ui/react-accordion", "1.2.20"),
    description: "Intrinsic-height disclosure with retained panel exits.",
    docsPath: "/components/animated-accordion",
    exportName: "AnimatedAccordion",
    motion: {
      controlled: true,
      enter: true,
      exit: true,
      intrinsicSize: true,
      layout: false,
      reducedMotion: true,
      replay: true,
      viewport: false,
    },
    name: "Animated Accordion",
    packageName: "easecraft",
    slug: "animated-accordion",
    sourceFiles: sourceFiles("animated-accordion"),
    status: "implemented",
  },
] as const satisfies readonly ComponentRegistryEntry[];

export type ComponentSlug = (typeof componentEntries)[number]["slug"];
